name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BUCKET_MULTIVERSO_ARANHA: your_bucket_value_here
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Deploy to S3
        run: aws s3 sync . s3://${{ env.BUCKET_MULTIVERSO_ARANHA }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
